### PR TITLE
Upgrade to Strapi v4

### PR DESCRIPTION
**Pull request by crcastle**
This PR upgrades this example repository to v4 of Strapi.

### CODE REVIEW

**Comment by MikkelScheike** [comment]
Do you have any indication on when this branch will get merged?

**Comment by MikkelScheike** [comment]
@crcastle I just saw Strapi got updated to v4.1.5. Do you think we will be able to get this version within a foreseeable time (and committed)? Thanks

**Comment by crcastle** [comment]
Hi @MikkelScheike- I'm working on it and hoping to get it complete today. The upgrade process has been a bit more complex than I had expected.

**Comment by crcastle** [comment]
Merging this PR and then will do a quick follow-up to update this report to Strapi v4.1.5.

**Comment by crcastle** [comment]
@MikkelScheike - This repo has been updated to Strapi v4.1.5 now.

**Pull request merged**
